version: "3.9"

services:
  web:
    ports:
      - 8443:8443
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      SAMHSTN_ASSETS_BUCKET: ${SAMHSTN_ASSETS_BUCKET}
    build:
      context: .
      dockerfile: web.Dockerfile
    depends_on:
      - build

  build:
    build:
      context: .
      dockerfile: build.Dockerfile
