version: 0.2

env:
  variables:
    CODEBUILD_BADGE: $(aws codebuild batch-get-projects --name CodeBuild --query "projects[0].badge.badgeRequestUrl" --output text)

phases:
  build:
    commands:
      - aws s3 sync static s3://samhstn.com
      - aws s3 cp s3://samhstn.com/repo/samhstn.com/badge.svg s3://samhstn.com/repo/samhstn.com/badge.svg --metadata "Website-Redirect-Location=$CODEBUILD_BADGE"
