version: 0.2

phases:
  build:
    commands:
      - |
      STACKS=(acm s3 cloudfront codebuild master-pipeline)
      for stack in $STACKS;do
        if diff --ignore-blank-lines $FILE <(
          aws cloudformation get-template --stack-name $stack --query TemplateBody --output text
        );then
          aws cloudformation update-stack \
            --stack-name $stack \
            --template-body file://infra/$stack.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameters ParameterKey=GithubPAToken,UsePreviousValue=true
          aws cloudformation wait stack-update-complete --stack-name $stack
        else
          echo "Template $stack is up to date!"
        fi
      done
      - aws s3 sync static s3://samhstn.com --delete --exclude badge
      - |
        CODEBUILD_BADGE_URL=$(\
          aws codebuild batch-get-projects \
            --name Push \
            --query "projects[0].badge.badgeRequestUrl" \
            --output text \
        )
        if ! aws s3 ls s3://samhstn.com/badge || \
          [ $(\
            aws s3api head-object \
              --bucket samhstn.com \
              --key badge \
              --query "Metadata.\"website-redirect-location\"" \
              --output text\
            ) != $CODEBUILD_BADGE_URL ];then
            curl https://s3.amazonaws.com/codefactory-us-east-1-prod-default-build-badges/unknown.svg > ./badge.svg
            aws s3 cp ./badge.svg s3://samhstn.com/badge --metadata "Website-Redirect-Location=$CODEBUILD_BADGE_URL"
        fi
