version: 0.2

phases:
  build:
    commands:
      - aws s3 sync static s3://samhstn.com
      - |
        CODEBUILD_BADGE=$(aws codebuild batch-get-projects --name CodeBuild --query "projects[0].badge.badgeRequestUrl" --output text)
        aws s3 cp s3://samhstn.com/repo/samhstn/badge.svg s3://samhstn.com/repo/samhstn/badge.svg --metadata "Website-Redirect-Location=$CODEBUILD_BADGE"
