version: 0.2

phases:
  install:
    commands:
      - apt-get update && apt-get install python3 python3-pip -y
      - pip3 install -vU setuptools
      - pip3 install cfn-lint
  build:
    commands:
      - |
        for FILE in $(ls infra/*.yaml infra/base/*.yaml);do
          if ! aws cloudformation validate-template --template-body "file://$FILE";then
            echo "ERR: INVALID TEMPLATE $FILE"
            exit 1
          fi
        done
      - cfn-lint infra/*.yaml infra/base/*.yaml
      - npm test
