version: 0.2

phases:
  install:
    commands:
      - apt-get update && apt-get install python3 python3-pip -y
      - pip3 install -vU setuptools
      - pip3 install cfn-lint
  build:
    commands:
      - |
        FILES=(
          ./infra/route53.yaml
          ./infra/iam.yaml
          ./infra/master_pipeline.yaml
          ./infra/acm.yaml
          ./infra/codebuild.yaml
          ./infra/s3.yaml
          ./infra/cloudfront.yaml
          ./infra/base/iam.yaml
          ./infra/base/email.yaml
        )
        for FILE in $FILES;do
          if ! aws cloudformation validate-template --template-body "file://$FILE";then
            echo "ERR: INVALID TEMPLATE $FILE"
            exit 1
          fi
        done
      - cfn-lint infra/*.yaml infra/base/*.yaml
      - npm test
