AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Point our domain name at our cloudfront distribution

Parameters:
  DomainName:
    Type: String
    Default: samhstn.com

Resources:
  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties: 
      Name: !Ref DomainName
      Comment: Points our domain name at our cloudfront distribution
      Type: A
      HostedZoneName: !Sub "{DomainName}."
      AliasTarget:
        DNSName: !ImportValue SamhstnCloudFrontDomainName
        HostedZoneId: Z2FDTNDATAQYW2 # default HostedZoneId for Cloudfront
