AWSTemplateFormatVersion: 2010-09-09

Description: >
  TODO

Parameters:
  NotificationEmail:
    Type: String
  FromEmail:
    Type: String
    Default: hello@samhstn.com

Resources:
  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: samhstn.com
      Type: MX
      HostedZoneName: samhstn.com.
      TTL: "300"
      ResourceRecords:
        - !Sub "10 inbound-smtp.${AWS::Region}.amazonaws.com"

  EmailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: samhstn-emails
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true

  EmailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref EmailBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                ses.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub ${EmailBucket.Arn}/*

  EmailRuleSet:
    Type: AWS::SES::ReceiptRuleSet
    Properties:
      RuleSetName: SamhstnRuleSet

  EmailRule:
    Type: AWS::SES::ReceiptRule
    Properties:
      RuleSetName: !Ref EmailRuleSet
      Rule:
        Name: SamhstnRule
        Enabled: true
        Recipients:
          - samhstn.com
        ScanEnabled: true
        Actions:
          - LambdaAction:
              FunctionArn: !GetAtt Lambda.Arn
          - S3Action:
              BucketName: !Ref EmailBucket
    DependsOn: EmailBucketPolicy

  SESLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: receive_email
      Principal: ses.amazonaws.com
      SourceAccount: !Sub ${AWS::AccountId}
    DependsOn: Lambda

  EmailRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ReceiveEmail
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: receive-email
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

  EmailTemplate:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://samhstn-root-cfn-templates.s3.amazonaws.com/email-template.yaml

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: receive_email
      Handler: index.handler
      Role: !GetAtt EmailRole.Arn
      Runtime: nodejs8.10
      Environment:
        Variables:
          NOTIFICATION_EMAIL: !Ref NotificationEmail
          FROM_EMAIL: !Ref FromEmail
      S3Bucket: samhstn-cfn-templates
      S3Key: email.js
