AWSTemplateFormatVersion: 2010-09-09

Description: >
  Sets up notifying our NotificationEmail email address whenever an email is sent to any @samhstn.com email address and writes the content of this email to an samhstn-emails S3 bucket

Parameters:
  NotificationEmail:
    Type: String
  FromEmail:
    Type: String
    Default: hello@samhstn.com

Resources:
  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: samhstn.com
      Type: MX
      HostedZoneName: samhstn.com.
      TTL: "300"
      ResourceRecords:
        - !Sub "10 inbound-smtp.${AWS::Region}.amazonaws.com"

  EmailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !ImportValue EmailBucketName
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                ses.amazonaws.com
            Action: s3:PutObject
            Resource:
              Fn::Sub:
                - "arn:aws:s3:::${EmailBucketName}/*"
                - EmailBucketName: !ImportValue EmailBucketName

  EmailRule:
    Type: AWS::SES::ReceiptRule
    DependsOn: EmailBucketPolicy
    Properties:
      RuleSetName: !ImportValue EmailRuleSetName
      Rule:
        Name: SamhstnRule
        Enabled: true
        Recipients:
          - samhstn.com
        ScanEnabled: true
        Actions:
          - LambdaAction:
              FunctionArn: !GetAtt Lambda.Arn
          - S3Action:
              BucketName: !ImportValue EmailBucketName

  SESLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn: Lambda
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: receive_email
      Principal: ses.amazonaws.com
      SourceAccount: !Sub ${AWS::AccountId}

  EmailRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ReceiveEmail
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: receive-email
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: receive_email
      Handler: index.handler
      Role: !GetAtt EmailRole.Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          NOTIFICATION_EMAIL: !Ref NotificationEmail
          FROM_EMAIL: !Ref FromEmail
      Code:
        S3Bucket: !ImportValue CloudformationBucketName
        S3Key: receive_email.zip

  EmailTemplate:
    Type: AWS::SES::Template
    Properties:
      Template:
        TemplateName: SamhstnTemplate
        SubjectPart: "@samhstn email from: {{from}}, to: {{to}}, with subject: {{subject}}"
        HtmlPart: |
          <!DOCTYPE html>
          <html>
          <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet" type="text/css">
            <style type="text/css">
              @import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro);
              body {
                margin: 0;
                padding: 0;
                -webkit-text-size-adjust: 100%;
                -ms-text-size-adjust: 100%;
              }
              table,
              td {
                border-collapse: collapse;
                mso-table-lspace: 0pt;
                mso-table-rspace: 0pt;
              }
              @media only screen and (max-width:480px) {
                @-ms-viewport { width: 320px; }
                @viewport { width: 320px; }
              }
              @media only screen and (min-width:480px) {
                .mj-column-per-100 {
                  width: 100% !important;
                  max-width: 100%;
                }
              }
            </style>
          </head>
          <body>
            <div style="margin:0px auto;max-width:800px;">
              <table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="width:100%;">
                <tbody>
                  <tr>
                    <td style="direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;">
                      <div class="mj-column-per-100 outlook-group-fix" style="font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;">
                        <table border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%">
                          <tr>
                            <td align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;">
                              <div style="font-family:'Source Sans Pro', sans-serif;font-size:20px;line-height:1;text-align:left;color:#276090;"> We've received an @samhstn.com email: </div>
                            </td>
                          </tr>
                          <tr>
                            <td align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;">
                              <div style="font-family:'Source Sans Pro', sans-serif;font-size:20px;line-height:1;text-align:left;color:#276090;"> > from: {{from}} </div>
                            </td>
                          </tr>
                          <tr>
                            <td align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;">
                              <div style="font-family:'Source Sans Pro', sans-serif;font-size:20px;line-height:1;text-align:left;color:#276090;"> > to: {{to}} </div>
                            </td>
                          </tr>
                          <tr>
                            <td align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;">
                              <div style="font-family:'Source Sans Pro', sans-serif;font-size:20px;line-height:1;text-align:left;color:#276090;"> > subject: {{subject}} </div>
                            </td>
                          </tr>
                          <tr>
                            <td style="font-size:0px;padding:10px 25px;word-break:break-word;">
                              <p style="border-top:solid 1px lightgrey;font-size:1;margin:0px auto;width:100%;"> </p>
                            </td>
                          </tr>
                          <tr>
                            <td align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;">
                              <div style="font-family:'Source Sans Pro', sans-serif;font-size:20px;line-height:1;text-align:left;color:#276090;"> See s3 bucket for email: {{messageId}}</div>
                            </td>
                          </tr>
                        </table>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </body>
          </html>
