AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Bucket:
    Type: String

Resources:
  PublicBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal: "*"
          Action: s3:GetObject
          Resource: !Sub arn:aws:s3:::${Bucket}/*
