AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: >-
  + creates a certificate to use on each build
  + creates and stores secrets
  + creates and exposes lambda function to be triggered by Github webhook

Parameters:
  GithubPAToken:
    Type: String
    NoEcho: true

  GithubMasterBranch:
    Type: String
    Default: master

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: samhstn.com
      SubjectAlternativeNames:
        - "*.samhstn.com"
      ValidationMethod: DNS

  GithubSecretParameter:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /GithubSecret
      GenerateSecretString:
        ExcludePunctuation: true

  GithubPATokenParameter:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /GithubPAToken
      SecretString: !Ref GithubPAToken

  WebhookFunction:
    Type: AWS::Serverless::Function
    DependsOn: GithubSecretParameter
    Properties:
      FunctionName: Webhook
      Runtime: nodejs12.x
      Role: !GetAtt WebhookLambdaRole.Arn
      Handler: webhook.handler
      Environment:
        Variables:
          GITHUB_MASTER_BRANCH: !Ref GithubMasterBranch
      CodeUri: s3://samhstn-cfn-templates/webhook/webhook.zip
      Events:
        Webhook:
          Type: HttpApi
          Properties:
            Method: POST
            Path: /webhook

  WebhookLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ExecuteWebhook
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: execute-webhook
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

Outputs:
  CertificateArn:
    Value: !Ref Certificate
    Export:
      Name: SamhstnCertificateArn

  WebhookEndpoint:
    Value: !Sub https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/webhook
