AWSTemplateFormatVersion: 2010-09-09

Parameters:
  SamhstnHostedZoneId:
    Type: String
    Default: Z2Z3JU4BX2KPG7
  SamhstnAccountId:
    Type: String
    Default: 741557730458

Resources:
  SamhstnBasePolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref SamhstnBaseRole
      PolicyName: SamhstnBasePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource: !Sub arn:aws:route53:::hostedzone/${SamhstnHostedZoneId}
            Action: route53:*
          - Effect: Allow
            Resource: '*'
            Action: route53:ListHostedZones
          - Effect: Allow
            Resource: arn:aws:s3:::samhstn-emails/*
            Action:
              - s3:ListBucket
              - s3:GetObject
          - Effect: Allow
            Resource: '*'
            Action: cloudformation:*

  SamhstnBaseRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SamhstnBase
      MaxSessionDuration: 43200
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${SamhstnAccountId}:user/admin
            Action: sts:AssumeRole
