AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Project:
    Type: String
    Description: "Project name in Pascal case"
  HostedZoneId:
    Type: String
  AccountId:
    Type: String

Resources:
  BasePolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref BaseRole
      PolicyName: BasePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource: !Sub arn:aws:route53:::hostedzone/${HostedZoneId}
            Action: route53:*
          - Effect: Allow
            Resource: '*'
            Action:
              - route53:List*
              - route53:Get*
          - Effect: Allow
            Resource: arn:aws:s3:::samhstn-emails/*
            Action:
              - s3:ListBucket
              - s3:GetObject
          - Effect: Allow
            Resource: '*'
            Action:
              - cloudformation:Describe*
              - cloudformation:List*
              - cloudformation:Get*
              - cloudformation:Create*
              - cloudformation:Update*
              - cloudformation:DeleteStack
          - Effect: Allow
            Resource: '*'
            Action:
              - ses:List*
              - ses:GetIdentity*

  BaseRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Project}Base
      MaxSessionDuration: 43200
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AccountId}:user/admin
            Action: sts:AssumeRole
