AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DomainName:
    Type: String
  CloudFrontDomainName:
    Type: String

Resources:
  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties: 
      Name: !Ref DomainName
      Comment: Points our domain name at our cloudfront distribution
      Type: A
      HostedZoneName: !Sub "${DomainName}."
      AliasTarget:
        DNSName: !Ref CloudFrontDomainName
        HostedZoneId: Z2FDTNDATAQYW2 # default HostedZoneId for Cloudfront
