version: 0.2

phases:
  build:
    commands:
      - aws cloudformation deploy
          --stack-name "samhstn-${ISSUE_NUMBER}-nat-gateway"
          --template-file infra/samhstn/nat-gateway.yml
          --no-fail-on-empty-changeset
          --parameter-overrides
            $(aws cloudformation describe-stacks
              --stack-name "samhstn-${ISSUE_NUMBER}-vpc"
              --query "Stacks[0].Outputs[*].[join('=', [OutputKey, OutputValue])] | join(' ', [])"
              --output text)
      - aws autoscaling complete-lifecycle-action \
          --lifecycle-hook-name "${LIFECYCLE_HOOK_NAME}" \
          --auto-scaling-group-name "${AUTOSCALING_GROUP_NAME}" \
          --lifecycle-action-token "${LIFECYCLE_ACTION_TOKEN}" \
          --lifecycle-action-result CONTINUE
