version: 0.2

phases:
  install:
    commands:
      - mix deps.get
  pre_build:
    commands:
      - mix test
  build:
    commands:
      - mix phx.digest
      - MIX_ENV=prod mix release
      - echo $S3_CODEBUILD_BUCKET_NAME
      - zip -r ${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip assets
      - zip -r ${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip _build/prod/rel/samhstn
      - zip -j ${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip
          infra/samhstn/appspec.yml
          infra/samhstn/start-service.sh
          infra/samhstn/stop-service.sh
      - aws s3 cp ${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip
          s3://${S3_CODEBUILD_BUCKET_NAME}/${ISSUE_NUMBER}/${CODEBUILD_RESOLVED_SOURCE_VERSION}
  post_build:
    commands:
      - ./infra/scripts/deploy_dynamic_build.sh
