version: 0.2

phases:
  install:
    commands:
      - mix deps.get
  pre_build:
    commands:
      - MIX_ENV=test mix compile
      - mix test
  build:
    commands:
      - MIX_ENV=prod mix compile
      - MIX_ENV=prod mix release
      - echo $S3_CODEBUILD_BUCKET_NAME
      - zip -j ${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip
          infra/samhstn/{appspec.yml,{start,stop}-service.sh}
          _build/prod/rel/samhstn/bin/samhstn
      - aws s3 cp ${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip
          s3://${S3_CODEBUILD_BUCKET_NAME}/${ISSUE_NUMBER}/${CODEBUILD_RESOLVED_SOURCE_VERSION}
  post_build:
    commands:
      - ./infra/scripts/deploy_dynamic_build.sh
