version: 0.2

phases:
  install:
    commands:
      - mix deps.get
  pre_build:
    commands:
      - MIX_ENV=test mix compile
      - MIX_ENV=test mix format --check-formatted
      - mix test
  build:
    commands:
      - mix phx.digest
      - MIX_ENV=prod mix release
      - echo $S3_CODEBUILD_BUCKET_NAME
      - zip -r ${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip priv
      - zip -qr ${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip _build/prod/rel/samhstn
      - zip -j ${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip
          infra/samhstn/appspec.yml
          infra/samhstn/start-service.sh
          infra/samhstn/stop-service.sh
      - aws s3 cp ${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip
          s3://${S3_CODEBUILD_BUCKET_NAME}/${ISSUE_NUMBER}/${CODEBUILD_RESOLVED_SOURCE_VERSION}
  post_build:
    commands:
      - aws cloudformation deploy
          --stack-name "samhstn-${ISSUE_NUMBER}"
          --template-file infra/samhstn/deploy.yml
          --no-fail-on-empty-changeset
          --capabilities CAPABILITY_IAM
          --parameter-overrides
            "GithubBranch=${CODEBUILD_SOURCE_VERSION}"
            "CodeBuildBucketKey=${ISSUE_NUMBER}/${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - DYNAMIC_BUILD=$(aws cloudformation describe-stacks --stack-name samhstn-$ISSUE_NUMBER)
      - LOAD_BALANCER_DNS_NAME=$(echo $DYNAMIC_BUILD | jp -u "Stacks[*].Outputs[?OutputKey=='LoadBalancerDNSName'].OutputValue|[0][0]")
      - LOAD_BALANCER_HOSTED_ZONE_ID=$(echo $DYNAMIC_BUILD | jp -u "Stacks[*].Outputs[?OutputKey=='LoadBalancerHostedZoneId'].OutputValue|[0][0]")
      - ASSUME_ROLE=$(aws sts assume-role
          --role-arn $ROUTE_53_ROLE_ARN
          --role-session-name root
          --duration-seconds 900)
      - aws configure --profile root set aws_access_key_id $(echo $ASSUME_ROLE | jp -u 'Credentials.AccessKeyId')
      - aws configure --profile root set aws_secret_access_key $(echo $ASSUME_ROLE | jp -u 'Credentials.SecretAccessKey')
      - aws configure --profile root set aws_session_token $(echo $ASSUME_ROLE | jp -u 'Credentials.SessionToken')
      - |
        #!/bin/bash
        set -e

        cat <<EOF > change-batch.json
        {
          "Changes": [
            {
              "Action": "UPSERT",
              "ResourceRecordSet": {
                "Name": "$ISSUE_NUMBER.samhstn.com",
                "Type": "A",
                "AliasTarget": {
                  "HostedZoneId": "$LOAD_BALANCER_HOSTED_ZONE_ID",
                  "DNSName": "$LOAD_BALANCER_DNS_NAME",
                  "EvaluateTargetHealth": false
                }
              }
            }
          ]
        }
        EOF

        aws route53 change-resource-record-sets \
          --profile root \
          --hosted-zone-id $SAMHSTN_HOSTED_ZONE_ID \
          --change-batch file://change-batch.json

cache:
  paths:
    - _build
    - priv/plts
