version: 0.2

phases:
  build:
    commands:
      - aws cloudformation describe-stacks
        --stack-name samhstn-123
        --query "Stacks[0].Outputs[?OutputKey=='LoadBalancerDNSName'].OutputValue|[0]"
        --output text
      - echo "ROUTE_53_ROLE_ARN = $ROUTE_53_ROLE_ARN"
      - ./infra/samhstn/assume-role.sh $ROUTE_53_ROLE_ARN root
      - aws route53 --profile root list-hosted-zones

  # install:
  #   commands:
  #     - mix deps.get
  # pre_build:
  #   commands:
  #     - MIX_ENV=test mix compile
  #     - mix test
  # build:
  #   commands:
  #     - mix phx.digest
  #     - MIX_ENV=prod mix release
  #     - echo $S3_CODEBUILD_BUCKET_NAME
  #     - zip -r ${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip priv
  #     - zip -qr ${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip _build/prod/rel/samhstn
  #     - zip -j ${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip
  #         infra/samhstn/appspec.yml
  #         infra/samhstn/start-service.sh
  #         infra/samhstn/stop-service.sh
  #     - aws s3 cp ${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip
  #         s3://${S3_CODEBUILD_BUCKET_NAME}/${ISSUE_NUMBER}/${CODEBUILD_RESOLVED_SOURCE_VERSION}
  # post_build:
  #   commands:
  #     - aws cloudformation deploy
  #         --stack-name "samhstn-${ISSUE_NUMBER}"
  #         --template-file infra/samhstn/dynamic-build.yml
  #         --no-fail-on-empty-changeset
  #         --capabilities CAPABILITY_IAM
  #         --parameter-overrides
  #           "GithubBranch=${CODEBUILD_SOURCE_VERSION}"
  #           "CodeBuildBucketKey=${ISSUE_NUMBER}/${CODEBUILD_RESOLVED_SOURCE_VERSION}"
  #     - LOAD_BALANCER_DNS_NAME=$(
  #       aws cloudformation describe-stacks
  #         --stack-name samhstn-123
  #         --query "Stacks[0].Outputs[?OutputKey=='LoadBalancerDNSName'].OutputValue|[0]"
  #         --output text
  #       )
  #     - echo $LOAD_BALANCER_DNS_NAME
  #     - aws cloudformation describe-stacks
  #         --profile 
