version: 0.2

phases:
  install:
    commands:
      - mix deps.get
  pre_build:
    commands:
      - MIX_ENV=test mix compile
      - mix test
  build:
    commands:
      - mix phx.digest
      - MIX_ENV=prod mix release
      - echo $S3_CODEBUILD_BUCKET_NAME
      - zip -r ${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip priv
      - zip -qr ${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip _build/prod/rel/samhstn
      - zip -j ${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip
          infra/samhstn/appspec.yml
          infra/samhstn/start-service.sh
          infra/samhstn/stop-service.sh
      - aws s3 cp ${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip
          s3://${S3_CODEBUILD_BUCKET_NAME}/${ISSUE_NUMBER}/${CODEBUILD_RESOLVED_SOURCE_VERSION}
  post_build:
    commands:
      - aws cloudformation deploy
          --stack-name "samhstn-${ISSUE_NUMBER}-vpc"
          --template-file infra/samhstn/vpc.yml
          --no-fail-on-empty-changeset
      - aws cloudformation deploy
          --stack-name "samhstn-${ISSUE_NUMBER}-nat-gateway"
          --template-file infra/samhstn/nat-gateway.yml
          --no-fail-on-empty-changeset
          --parameter-overrides
            $(aws cloudformation describe-stacks
              --stack-name "samhstn-${ISSUE_NUMBER}-vpc"
              --query "Stacks[0].Outputs[*].[join('=', [OutputKey, OutputValue])] | join(' ', [])"
              --output text)
      - aws cloudformation deploy
          --stack-name "samhstn-${ISSUE_NUMBER}"
          --template-file infra/samhstn/dynamic-build.yml
          --no-fail-on-empty-changeset
          --capabilities CAPABILITY_IAM
          --parameter-overrides
            "GithubBranch=${CODEBUILD_SOURCE_VERSION}"
            "CodeBuildBucketKey=${ISSUE_NUMBER}/${CODEBUILD_RESOLVED_SOURCE_VERSION}"
            $(aws cloudformation describe-stacks
              --stack-name "samhstn-${ISSUE_NUMBER}-vpc"
              --query "Stacks[0].Outputs[*].[join('=', [OutputKey, OutputValue])] | join(' ', [])"
              --output text)
