version: 0.2

phases:
  install:
    commands:
      - mix deps.get
  build:
    commands:
      - # mix test
  post_build:
    commands:
      - echo "CODEBUILD_RESOLVED_SOURCE_VERSION ${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - echo "CODEBUILD_SOURCE_VERSION ${CODEBUILD_SOURCE_VERSION}"
      - echo "ISSUE NUMBER ${ISSUE_NUMBER}"
      - aws cloudformation deploy --stack-name samhstn-${ISSUE_NUMBER} --template-file ./infra/samhstn/dynamic-build.yml --capabilities CAPABILITY_IAM --parameter-overrides "GithubBranch=${CODEBUILD_SOURCE_VERSION}"
