version: 0.2

env:
  shell: bash

phases:
  build:
    commands:
      - DYNAMIC_BUILD=$(aws cloudformation describe-stacks --stack-name samhstn-${ISSUE_NUMBER})
      - LOAD_BALANCER_DNS_NAME=$(echo $DYNAMIC_BUILD | jp -u "Stacks[*].Outputs[?OutputKey=='LoadBalancerDNSName'].OutputValue|[0][0]")
      - LOAD_BALANCER_HOSTED_ZONE_ID=$(echo $DYNAMIC_BUILD | jp -u "Stacks[*].Outputs[?OutputKey=='LoadBalancerHostedZoneId'].OutputValue|[0][0]")
      - aws cloudformation delete-stack --stack-name samhstn-${ISSUE_NUMBER}
      - ASSUME_ROLE=$(aws sts assume-role
          --role-arn $ROUTE_53_ROLE_ARN
          --role-session-name root
          --duration-seconds 900)
      - aws configure --profile root set aws_access_key_id $(echo $ASSUME_ROLE | jp -u 'Credentials.AccessKeyId')
      - aws configure --profile root set aws_secret_access_key $(echo $ASSUME_ROLE | jp -u 'Credentials.SecretAccessKey')
      - aws configure --profile root set aws_session_token $(echo $ASSUME_ROLE | jp -u 'Credentials.SessionToken')
      - |
        set -e

        cat <<EOF > change-batch.json
        {
          "Changes": [
            {
              "Action": "DELETE",
              "ResourceRecordSet": {
                "Name": "$ISSUE_NUMBER.samhstn.com",
                "Type": "A",
                "AliasTarget": {
                  "HostedZoneId": "$LOAD_BALANCER_HOSTED_ZONE_ID",
                  "DNSName": "$LOAD_BALANCER_DNS_NAME",
                  "EvaluateTargetHealth": false
                }
              }
            }
          ]
        }
        EOF

        aws route53 change-resource-record-sets \
          --profile root \
          --hosted-zone-id $SAMHSTN_HOSTED_ZONE_ID \
          --change-batch file://change-batch.json
