version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - aws s3 cp --recursive --quiet s3://${MASTER_BUILD_CACHE_BUCKET_NAME}/_build _build || true
      - aws s3 cp --recursive --quiet s3://${MASTER_BUILD_CACHE_BUCKET_NAME}/deps deps || true
      - aws s3 cp --recursive --quiet s3://${MASTER_BUILD_CACHE_BUCKET_NAME}/priv/plts priv/plts || true
      - mix deps.get
  pre_build:
    commands:
      - MIX_ENV=test mix compile --force
      - MIX_ENV=test mix dialyzer
      - MIX_ENV=test mix format --check-formatted
      - MIX_ENV=test mix sobelow --router lib/samhstn_web/router.ex --exit --skip
      - mix test
  build:
    commands:
      - MIX_ENV=prod mix phx.digest
      - MIX_ENV=prod mix release
      - mv infra/samhstn/{appspec.yml,start-service.sh,stop-service.sh} .
  post_build:
    commands:
      - aws s3 sync --delete --quiet _build/prod/lib s3://${MASTER_BUILD_CACHE_BUCKET_NAME}/_build/prod/lib
      - aws s3 sync --delete --quiet _build/test s3://${MASTER_BUILD_CACHE_BUCKET_NAME}/_build/test
      - aws s3 sync --delete --quiet deps s3://${MASTER_BUILD_CACHE_BUCKET_NAME}/deps
      - aws s3 sync --delete --quiet priv/plts s3://${MASTER_BUILD_CACHE_BUCKET_NAME}/priv/plts

artifacts:
  files:
    - start-service.sh
    - stop-service.sh
    - appspec.yml
    - 'priv/static/**/*'
    - '_build/prod/rel/samhstn/**/*'
