version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - aws s3 cp --recursive s3://${MASTER_BUILD_CACHE_BUCKET_NAME}/_build _build
      - aws s3 cp --recursive s3://${MASTER_BUILD_CACHE_BUCKET_NAME}/deps deps
      - mix deps.get
  pre_build:
    commands:
      - MIX_ENV=test mix compile
      - MIX_ENV=test mix format --check-formatted
      - mix test
  build:
    commands:
      - mix phx.digest
      - MIX_ENV=prod mix release
      - mv infra/samhstn/{appspec.yml,start-service.sh,stop-service.sh} .
  post_build:
    commands:
      - aws s3 sync --delete _build s3://${MASTER_BUILD_CACHE_BUCKET_NAME}/_build
      - aws s3 sync --delete deps s3://${MASTER_BUILD_CACHE_BUCKET_NAME}/deps

artifacts:
  files:
    - start-service.sh
    - stop-service.sh
    - appspec.yml
    - 'priv/static/**/*'
    - '_build/prod/rel/samhstn/**/*'
