AWSTemplateFormatVersion: 2010-09-09

Description: >
  Creates a cross account, root access role for a project admin to assume.
  Specifies the resources for this role to access in our root (master billing) account.

Parameters:
  Project:
    Type: String
    Description: "Project name in pascal case, e.g. Samhstn"
  HostedZoneId:
    Type: String
    Description: "Route53 hosted zone ref for our domain name, e.g. "
  AccountId:
    Type: String
    Description: "Account to grant root access"

Resources:
  RootPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref RootRole
      PolicyName: RootPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource: !Sub arn:aws:route53:::hostedzone/${HostedZoneId}
            Action: route53:*
          - Effect: Allow
            Resource: '*'
            Action:
              - route53:List*
              - route53:Get*
          - Effect: Allow
            Resource: '*'
            Action:
              - s3:ListBucket
              - s3:ListAllMyBuckets
              - s3:CreateBucket
              - s3:PutObject
              - s3:DeleteBucket
              - s3:DeleteObject
              - s3:PutBucket
              - s3:GetObject
          - Effect: Allow
            Resource: '*'
            Action:
              - cloudformation:Describe*
              - cloudformation:List*
              - cloudformation:Get*
              - cloudformation:Create*
              - cloudformation:Update*
              - cloudformation:DeleteStack
          - Effect: Allow
            Resource: '*'
            Action:
              - ses:List*
              - ses:GetIdentity*
          - Effect: Allow
            Resource: '*'
            Action: sns:ListTopics
          - Effect: Allow
            Resource: '*'
            Action: iam:PutRolePolicy

  RootRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Project}Root
      MaxSessionDuration: 43200
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AccountId}:user/admin
            Action: sts:AssumeRole
