AWSTemplateFormatVersion: 2010-09-09

Description: >
  Sets up s3 buckets and other resources which are difficult to tear down and spin up programatically.

Parameters:
  CloudformationBucket:
    Type: String
    Description: S3 bucket for storing our cloudformation templates and other referenced files.

Resources:
  CloudformationS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref CloudformationBucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  CloudformationBucketName:
    Value: !Ref CloudformationS3Bucket
    Export:
      Name: CloudformationBucketName
