AWSTemplateFormatVersion: 2010-09-09

Parameters:
  GithubPAToken:
    Type: String
    NoEcho: true

Resources:
  GithubSecretParameter:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /GithubSecret
      GenerateSecretString:
        ExcludePunctuation: true

  GithubPATokenParameter:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /GithubPAToken
      SecretString: !Ref GithubPAToken
