AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Bucket:
    Type: String
  RootAccountId:
    Type: String
  AdminAccountId:
    Type: String

Resources:
  PrivateBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${RootAccountId}:role/SamhstnBase
            Action: s3:*
            Resource: !Sub arn:aws:s3:::${Bucket}/*
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AdminAccountId}:role/Admin
            Action: s3:GetObject
            Resource: !Sub arn:aws:s3:::${Bucket}/*
